### ISSUE TITLE
ROCm 7.1 / 7.1.1 Windows: MIOpen fails to compile BatchNorm forward kernel (type_traits not found, gfx1030)

### ISSUE THREAD

**Issue by underlover** [guinmoon/rocm7_builds#11]
Hi @guinmoon,

I’ve been using your ROCm Windows builds extensively to run ComfyUI, which runs perfectly fine, and I really appreciate your dedication to making stable, usable AMD GPU acceleration available on Windows. It’s been a huge help for many of us working with PyTorch on AMD hardware, and I wanted to thank you for your ongoing effort.

I’ve run into a consistent, reproducible issue across  recent releases: In  pytorch deep learning projects, any PyTorch model that contains `BatchNorm2d` or BatchNorm layers immediately crashes during inference/training due to a MIOpen JIT compilation failure. 

## Issue Summary
When executing a model with BatchNorm, MIOpen fails to compile the forward inference kernel with a fatal error:
`fatal error: 'type_traits' file not found`

This completely prevents GPU execution for any network using BatchNorm.

## Tested Releases
- ROCm7.1.1-20251207 GFX103X-all
- ROCm7.1-20251202 GFX103X-dgpu + GFX110X-all + ATTN

## Environment
- GPU: AMD RX 6950 XT (gfx1030)
- OS: Windows 11 Pro
- Python: 3.12
- Installation: Official `.whl` packages from your release page

## Full Error Log (paths cleaned)
```
MIOpen(HIP): Error [Compile] 'hiprtcCompileProgram(prog.get(), c_options.size(), c_options.data())' MIOpenBatchNormFwdInferSpatialHIP.cpp: HIPRTC_ERROR_COMPILATION (6)
MIOpen(HIP): Error [BuildHip] HIPRTC status = HIPRTC_ERROR_COMPILATION (6), source file: MIOpenBatchNormFwdInferSpatialHIP.cpp
MIOpen(HIP): Warning [BuildHip] In file included from C:\Users\82090\AppData\Local\Temp\comgr-9236-15-e7633b\input\MIOpenBatchNormFwdInferSpatialHIP.cpp:30:
In file included from C:\Users\....\AppData\Local\Temp\comgr-9236-15-e7633b\include\bnorm_spatial_activation_functions.hpp:32:
In file included from C:\Users\...\AppData\Local\Temp\comgr-9236-15-e7633b\include\configuration.hpp:36:
C:\Users\...\AppData\Local\Temp\comgr-9236-15-e7633b\include\miopen_type_traits.hpp:151:10: fatal error: 'type_traits' file not found
  151 | #include <type_traits>
      |          ^~~~~~~~~~~~~
1 error generated when compiling for gfx1030.
MIOpen Error: Mortar:D:/b/TheRock/rocm-libraries/projects/miopen/src/hipoc/hipoc_program.cpp:299: Code object build failed. Source: MIOpenBatchNormFwdInferSpatialHIP.cpp
Traceback (most recent call last):
  ......
  File "C:\Users\...\....py", line 93, in forward
    x = self.input_conv(x)
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\miniconda3\envs\rocm7\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\miniconda3\envs\rocm7\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\miniconda3\envs\rocm7\Lib\site-packages\torch\nn\modules\container.py", line 250, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "C:\Users\...\miniconda3\envs\rocm7\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\miniconda3\envs\rocm7\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\miniconda3\envs\rocm7\Lib\site-packages\torch\nn\modules\batchnorm.py", line 193, in forward
    return F.batch_norm(
           ^^^^^^^^^^^^^
  File "C:\Users\...\miniconda3\envs\rocm7\Lib\site-packages\torch\nn\functional.py", line 2813, in batch_norm
    return torch.batch_norm(
           ^^^^^^^^^^^^^^^^^
RuntimeError: miopenStatusUnknownError
```
## Purpose
I’m working on a PyTorch-based reinforcement learning project with a CNN backbone that relies on BatchNorm layers. The error appears **only when BatchNorm is present** and stops all GPU-accelerated training/inference.

## Request
Could you look into this MIOpen / HIPRTC issue related to missing C++ standard library headers on Windows? A fix or an official workaround (other than fully disabling MIOpen) would be extremely helpful.

Thank you again for your fantastic work on ROCm for Windows!

Best regards.

**Comment by wdx04** [comment]
Setting the correct Include/Lib environment variables can solve this(modify according to your actual path).

INCLUDE: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\include;C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0;C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt;C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\um;C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\shared

LIB: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\lib\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\um\x64

Additonally, setting MIOPEN_DISABLE_CACHE=0 and MIOPEN_ENABLE_FIND_MODE=0 may be useful.

**Comment by l9565495** [comment]
RX6700XT also have this problem.

**Comment by sabahmax-dev** [comment]
Hi @guinmoon,

I opened PR #13 to address issue #11. It fixes the MIOpen JIT compilation failure for BatchNorm forward kernels on ROCm 7.1 / 7.1.1 Windows builds by making the missing `<type_traits>` header available to the HIPRTC/COMGR compiler during kernel compilation. This should allow BatchNorm layers to run again on `gfx1030` without the `type_traits` error.

Thanks!
